# Generated by Django 3.0.3 on 2020-03-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='owner',
            new_name='author',
        ),
    ]
